name: catalog sync
on:
  push:
	  branches: 
	  - main

jobs:
  catalog_sync:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - download catalogs
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP/NCAR only
          args: "copy -v s3:cmip6-pds fs: --include /*.csv --include /*.json"
	  - name: list catalog files
		run: |
		  ls
