name: rclone sync
on:
  push:
    branches: 
      - main
  # runs 4x daily at 0,6,12,18:00 UTC
  #schedule:
  #  - cron: "0 */6 * * *"
jobs:
  CMIP__NCAR:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/NCAR/** --transfers 15 --checkers 65"
  CMIP__CNRM-CERFACS:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/CNRM-CERFACS/** --transfers 15 --checkers 65"
  CMIP__IPSL:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/IPSL/** --transfers 15 --checkers 65"	
  CMIP__CCCma:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/CCCma/** --transfers 15 --checkers 65"
  CMIP__MPI-M_NCC:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/{MPI-M,NCC}/** --transfers 15 --checkers 65"
  CMIP__EC-Earth-Consortium_NASA-GISS:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/{EC-Earth-Consortium,NASA-GISS}/** --transfers 15 --checkers 65"
  CMIP__NOAA-GFDL_BCC_AWI_CSIRO_SNU_CSIRO-ARCCSS:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/{NOAA-GFDL,BCC,AWI,CSIRO,SNU,CSIRO-ARCCSS}/** --transfers 15 --checkers 65"			  
  CMIP__remainder:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /CMIP/{NCAR,CNRM-CERFACS,IPSL,CCCma,MPI-M,NCC,EC-Earth-Consortium,NASA-GISS,NOAA-GFDL,BCC,AWI,CSIRO,SNU,CSIRO-ARCCSS}/**' --filter '+ /CMIP/**' --filter '- *' --transfers 15 --checkers 65"
  ScenarioMIP__CCCma:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/CCCma/** --transfers 15 --checkers 65"	
  ScenarioMIP__CNRM-CERFACS_IPSL:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/{CNRM-CERFACS,IPSL}/** --transfers 15 --checkers 65"			  
  ScenarioMIP__EC-Earth-Consortium_MIROC_NCAR:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/{EC-Earth-Consortium,MIROC,NCAR}/** --transfers 15 --checkers 65"
  ScenarioMIP__MPI-M_OHC_MRI_DKRZ:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/{MPI-M,OHC,MRI,DKRZ}/** --transfers 15 --checkers 65"
  ScenarioMIP__remainder:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /ScenarioMIP/{CCCma,CNRM-CERFACS,IPSL,EC-Earth-Consortium,MIROC,NCAR,MPI-M,OHC,MRI,DKRZ}/**' --filter '+ /ScenarioMIP/**' --filter '- *' --transfers 15 --checkers 65"
  DCPP__NCAR:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /DCPP/NCAR/** --transfers 15 --checkers 65"
  DCPP__CCCma:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /DCPP/CCCma/** --transfers 15 --checkers 65"
  DCPP__remainder:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /DCPP/{NCAR,CCCma}/**' --filter '+ /DCPP/**' --filter '- *' --transfers 15 --checkers 65"
  GFDL-CM26_HighResMIP_CMIP5:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /{GFDL_CM2_6,HighResMIP,CMIP5}/** --transfers 15 --checkers 65"
  remainder:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # remainder of directories left untouched
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --exclude /{CMIP,ScenarioMIP,DCPP,GFDL_CM2_6,HighResMIP,CMIP5}/** --exclude /*.json* --exclude /*.csv* --transfers 15 --checkers 65"
