name: CMIP6 sync
on:
  # runs 4x daily at 0,6,12,18:00 UTC
  schedule:
    - cron: "0 */6 * * *"
jobs:
  # CMIP/NCAR only
  CMIP__NCAR:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/NCAR/** --transfers 15 --checkers 65"
  # CMIP/CNRM-CERFACS only
  CMIP__CNRM-CERFACS:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/CNRM-CERFACS/** --transfers 15 --checkers 65"
  # CMIP/IPSL only
  CMIP__IPSL:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/IPSL/** --transfers 15 --checkers 65"
  # CMIP/CCCma only
  CMIP__CCCma:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/CCCma/** --transfers 15 --checkers 65"
  # CMIP/MPI-M, CMIP/NCC only
  CMIP__MPI-M_NCC:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/{MPI-M,NCC}/** --transfers 15 --checkers 65"
  # CMIP/EC-Earth-Consortium, CMIP/NASA-GISS only
  CMIP__EC-Earth-Consortium_NASA-GISS:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/{EC-Earth-Consortium,NASA-GISS}/** --transfers 15 --checkers 65"
  # CMIP/NOAA-GFDL, CMIP/BCC, CMIP/AWI, CMIP/CSIRO, CMIP/SNU, CMIP/CSIRO-ARCCSS
  CMIP__NOAA-GFDL_BCC_AWI_CSIRO_SNU_CSIRO-ARCCSS:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /CMIP/{NOAA-GFDL,BCC,AWI,CSIRO,SNU,CSIRO-ARCCSS}/** --transfers 15 --checkers 65"			  
  # CMIP remaining directories
  CMIP__remainder:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /CMIP/{NCAR,CNRM-CERFACS,IPSL,CCCma,MPI-M,NCC,EC-Earth-Consortium,NASA-GISS,NOAA-GFDL,BCC,AWI,CSIRO,SNU,CSIRO-ARCCSS}/**' --filter '+ /CMIP/**' --filter '- *' --transfers 15 --checkers 65"
  # ScenarioMIP/CCCma only
  ScenarioMIP__CCCma:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/CCCma/** --transfers 15 --checkers 65"	
  # ScenarioMIP/CNRM-CERFACS, ScenarioMIP/IPSL only
  ScenarioMIP__CNRM-CERFACS_IPSL:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with: 
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/{CNRM-CERFACS,IPSL}/** --transfers 15 --checkers 65"			  
  # ScenarioMIP/EC-Earth-Consortium, ScenarioMIP/MIROC, ScenarioMIP/NCAR only
  ScenarioMIP__EC-Earth-Consortium_MIROC_NCAR:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with: 
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/{EC-Earth-Consortium,MIROC,NCAR}/** --transfers 15 --checkers 65"
  # ScenarioMIP/MPI-M, ScenarioMIP/OHC, ScenarioMIP/MRI, ScenarioMIP/DKRZ
  ScenarioMIP__MPI-M_OHC_MRI_DKRZ:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/{MPI-M,OHC,MRI,DKRZ}/** --transfers 15 --checkers 65"
  # ScenarioMIP remaining directories
  ScenarioMIP__remainder:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /ScenarioMIP/{CCCma,CNRM-CERFACS,IPSL,EC-Earth-Consortium,MIROC,NCAR,MPI-M,OHC,MRI,DKRZ}/**' --filter '+ /ScenarioMIP/**' --filter '- *' --transfers 15 --checkers 65"
  # DCPP/NCAR only
  DCPP__NCAR:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /DCPP/NCAR/** --transfers 15 --checkers 65"
  # DCPP/CCCma only
  DCPP__CCCma:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /DCPP/CCCma/** --transfers 15 --checkers 65"
  # DCPP remaining directories
  DCPP__remainder:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /DCPP/{NCAR,CCCma}/**' --filter '+ /DCPP/**' --filter '- *' --transfers 15 --checkers 65"
  # GFDL_CM2_6, HighResMIP, CMIP5
  GFDL-CM26_HighResMIP_CMIP5:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /{GFDL_CM2_6,HighResMIP,CMIP5}/** --transfers 15 --checkers 65"
  # remaining directories
  remainder:
    runs-on: ubuntu-latest
    steps:
      - name: GCS to S3 sync
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --exclude /{CMIP,ScenarioMIP,DCPP,GFDL_CM2_6,HighResMIP,CMIP5}/** --exclude /*.{bin,csv,csv.gz,html,json,jsonl} --transfers 15 --checkers 65"
  # change GCS links in catalogs to S3 before uploading
  catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Download catalogs from GCS
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "copy -v gs:cmip6 fs: --include /*.{csv,json}"
      - name: Change catalog links from GCS to S3
        run: |
          for file in *; do sed -i 's/gs:\/\/cmip6/s3:\/\/cmip6-pds/g' $file; done
          for file in *.json; do sed -i 's/storage.googleapis.com\/cmip6/cmip6-pds.s3-us-west-2.amazonaws.com/g' $file; done  
      - name: Upload catalogs to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "copy -c -v fs: s3:cmip6-pds --include /*.{csv,json}"
