name: catalog sync

on:
  push:
    branches: [ main ]

jobs:
  catalog_sync:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - download catalogs
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "copy -v s3:cmip6-pds fs: --include /*.csv --include /*.json"

      - name: replace gs with s3
        run: for file in *; do echo $file; done
