name: catalog sync

on:
  push:
    branches: [ main ]

jobs:
  catalog_sync:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Download catalogs from GCS
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "copy -v gs:cmip6 fs: --include /*.csv --include /*.json"

      - name: replace gs with s3
        run: for file in *; do sed -i 's/gs:/s3:/g' $file; done
        
      - name: rclone - Upload catalogs to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          args: "copy -v fs: s3:cmip6-pds --include /*.csv --include /*.json"
